yarnPath: .yarn/releases/yarn-berry.cjs
npmScopes:
  picast-app:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${NPM_TOKEN}
packageExtensions:
  '@apollographql/apollo-tools@*':
    dependencies:
      graphql: '*'
  'typerpc@*':
    dependencies:
      ws: '*'
      chalk: '*'
  'jest@*':
    dependencies:
      jest-circus: '*'
