yarnPath: .yarn/releases/yarn-berry.cjs
npmScopes:
  picast-app:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${NPM_TOKEN}
packageExtensions:
  '@apollographql/apollo-tools@*':
    dependencies:
      graphql: '*'
  'typerpc@*':
    dependencies:
      ws: '*'
      chalk: '*'
  'styled-components@*':
    dependencies:
      babel-plugin-macros: '*'
      react-is: '*'
  'webpack@*':
    dependencies:
      chalk: '*'
      react-is: '*'
      react-dev-utils: '*'
  'webpack-dev-server@*':
    dependencies:
      chalk: '*'
      react-dev-utils: '*'
  'react-dev-utils@*':
    dependencies:
      chalk: '*'
