#import "./podcastInfo.gql"
#import "./episodeBase.gql"

fragment PodcastPageInfo on Podcast {
  ...PodcastInfo
  episodes(last: $limit) {
    pageInfo {
      total
      hasPreviousPage
      hasNextPage
    }
    edges {
      node {
        ...EpisodeBase
      }
      cursor
    }
  }
}
