#import "./episodeBase.gql"

fragment PodcastPageInfo on Podcast {
  id
  title
  author
  description
  artwork
  feed
  check
  episodes(last: 50) {
    pageInfo {
      total
      hasPreviousPage
      hasNextPage
    }
    edges {
      node {
        ...EpisodeBase
      }
      cursor
    }
  }
}
