fragment PodcastPageInfo on Podcast {
  id
  title
  author
  description
  artwork
  feed
  episodes(last: 50) {
    pageInfo {
      total
      hasPreviousPage
    }
    edges {
      node {
        id
        title
        publishDate
        file
      }
      cursor
    }
  }
}
