#import "./podcast.gql"

fragment MeInitial on User {
  id
  authProvider
  wsAuth
  subscriptions(known: $known) {
    added {
      ...PodcastPageInfo
    }
    removed
  }
  wpSubs
  currentEpisode {
    id {
      podcast
      episode
    }
  }
}
