query PodcastEpisodes($podcast: ID!, $last: Int!, $cursor: ID!) {
  podcast(id: $podcast) {
    id
    episodes(last: $last, before: $cursor) {
      pageInfo {
        total
        hasPreviousPage
      }
      edges {
        node {
          id
          title
          publishDate
          file
        }
        cursor
      }
    }
  }
}
