#import "../fragments/episodeBase.gql"

query PodcastEpisodes($podcast: ID!, $last: Int!, $cursor: ID) {
  podcast(id: $podcast) {
    id
    episodes(last: $last, before: $cursor) {
      pageInfo {
        total
        hasPreviousPage
        hasNextPage
      }
      edges {
        node {
          ...EpisodeBase
        }
        cursor
      }
    }
  }
}
